name: Build Dolar and Deploy

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    schedule:
        - cron: '*/30 * * * 1-5'
    workflow_dispatch:  # Permite ejecución manual del workflow

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Installing Dependencies
              run: npm install && npm install -g vercel

            - name: Vercel Auth
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Building
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploying
              run: |
                  TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
                  vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --name "Actualizacion Cotizaciones - ${TIMESTAMP}"
