# .github/workflows/update-build.yml
name: Build and Deploy

on:
  schedule:
   - cron: '*/10 * * * *'
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Astro
        run: npx astro build

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
