name: Build Dolar and Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: 

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Installing Dependencies
        run: bun install && bun add -g vercel

      - name: Vercel Auth
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Building
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploying
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}